RethinkRobotics-opensource/sns_ik

sns_ik_examples/src/test_sns_ik.cpp
sns_ik_lib/CMakeLists.txt
sns_ik_lib/include/sns_ik/sns_position_ik.hpp
sns_ik_lib/include/sns_ik/sns_velocity_ik.hpp
sns_ik_lib/src/sns_ik_math_utils.cpp
sns_ik_lib/src/sns_position_ik.cpp
sns_ik_lib/src/sns_velocity_ik.cpp

This is the first pass at a position IK solver, but it hasn't been full tested with a real robot chain yet.
Requires KDL as a dependency.

Position IK

---

sns_ik_examples/src/test_sns_ik.cpp
sns_ik_lib/CMakeLists.txt
sns_ik_lib/include/sns_ik/osns_sm_velocity_ik.hpp
sns_ik_lib/include/sns_ik/osns_velocity_ik.hpp
sns_ik_lib/include/sns_ik/sns_velocity_ik.hpp
sns_ik_lib/src/osns_sm_velocity_ik.cpp
sns_ik_lib/src/osns_velocity_ik.cpp
sns_ik_lib/src/sns_velocity_ik.cpp

Copies over the functionality of the Optimal SNS velocity IK solver. OSNSsmVelocityIK includes the scale margin factor.

Optimal SNS

---

sns_ik_examples/src/test_sns_ik.cpp
sns_ik_lib/include/sns_ik/sns_position_ik.hpp
sns_ik_lib/src/sns_position_ik.cpp

The position IK solver now converges!

Fixed Cartesian error math which was different from Eigen

---

sns_ik_lib/include/sns_ik/osns_sm_velocity_ik.hpp
sns_ik_lib/include/sns_ik/osns_velocity_ik.hpp
sns_ik_lib/include/sns_ik/sns_ik.hpp
sns_ik_lib/include/sns_ik/sns_ik_math_utils.hpp
sns_ik_lib/include/sns_ik/sns_velocity_ik.hpp
sns_ik_lib/src/sns_ik.cpp
sns_ik_lib/src/sns_position_ik.cpp
sns_ik_lib/src/sns_velocity_ik.cpp

* Some basic improvements to the position solver so that it stays within joint limits and stops if it gets stuck
* Added virtual symbol for proper inheritance
* Additional debug logging. Turn off later.

Additional debugging of position IK solver, plus added virtual symbols

---

sns_ik_examples/launch/test_ik_solvers.launch
sns_ik_examples/src/ik_tests.cpp
sns_ik_lib/src/sns_position_ik.cpp
sns_ik_lib/src/sns_velocity_ik.cpp

A few minor changes with parameters and logging. Random seed based on time. Small parameter changes.

A few minor changes.

---

sns_ik_examples/src/ik_tests.cpp
sns_ik_examples/src/test_sns_ik.cpp
sns_ik_lib/CMakeLists.txt
sns_ik_lib/include/sns_ik/fosns_velocity_ik.hpp
sns_ik_lib/include/sns_ik/fsns_velocity_ik.hpp
sns_ik_lib/include/sns_ik/sns_ik.hpp
sns_ik_lib/include/sns_ik/sns_ik_math_utils.hpp
sns_ik_lib/include/sns_ik/sns_velocity_ik.hpp
sns_ik_lib/src/fosns_velocity_ik.cpp
sns_ik_lib/src/fsns_velocity_ik.cpp
sns_ik_lib/src/sns_ik.cpp
sns_ik_lib/src/sns_ik_math_utils.cpp

* To get FSNS to work, fixed a bug in sns_ik_math_utils which was using abs instead of fabs.
* Looks like there may still be a bug in Fast-optimal-SNS, but that will be fixed after Ian merges this into is most recent testing framework.

Initial Fast and Fast-optimal SNS algorithm port

---

sns_ik_examples/src/ik_tests.cpp
sns_ik_lib/include/sns_ik/fsns_velocity_ik.hpp
sns_ik_lib/src/fosns_velocity_ik.cpp
sns_ik_lib/src/sns_ik_math_utils.cpp
sns_ik_lib/src/sns_position_ik.cpp
sns_ik_lib/src/sns_velocity_ik.cpp

Put in a test to see if the velocity was scaled correctly and checks that the new velocity is parallel to the desired direction. Only checks for linear velocity for now.

Velocity scaling test and additional logging opitions

---

sns_ik_examples/src/ik_tests.cpp
sns_ik_lib/include/sns_ik/sns_ik.hpp
sns_ik_lib/include/sns_ik/sns_position_ik.hpp
sns_ik_lib/src/sns_ik.cpp
sns_ik_lib/src/sns_position_ik.cpp

This Adds a shared_ptr get interface for the position and velocity solvers inside the SNS_IK class.
Also, it fills out the testing framework a bit by iterating over different types of velocity solvers.

Adds SharedPtr Get interface for Pos & Vel solvers

---

sns_ik_examples/src/ik_tests.cpp
sns_ik_lib/include/sns_ik/sns_position_ik.hpp

Fixed the build that I broke with changes for review #16. Reverted the `getChain()` interface & removed the invalid `setTolerance()` call.

Fixed Interface breakage & invalid function call

---

sns_ik_examples/launch/test_ik_solvers.launch
sns_ik_examples/src/ik_tests.cpp
sns_ik_lib/src/sns_ik.cpp
sns_ik_lib/src/sns_position_ik.cpp
sns_ik_lib/src/sns_velocity_ik.cpp

Also added a check if the urdf didn't include velocity limits.

Cleaner test output.

---

sns_ik_examples/launch/test_baxter.launch
sns_ik_examples/launch/test_ik_solvers.launch
sns_ik_examples/src/ik_tests.cpp

This PR cleans up some of the ROS Interface for testing, as suggested in #20 . Also, I added a hierarchical launch file structure so that the robot and joint limits can be loaded independent of the test_ik_solvers.launch file.

Testing interface standardized

---

sns_ik_examples/src/ik_tests.cpp

This commit adds Standard Deviation calculation for
the time each position solver takes to run, for KDL,
Trac & all SNS solvers.

Added Pos Solver Time Standard Deviation

---

sns_ik_examples/launch/test_ik_solvers.launch
sns_ik_examples/src/ik_tests.cpp

- Added the quantification of nullspace contribution vs the natural IK solution without using a nullspace
- Added additional position IK test conditions

Test nullspace

---

sns_ik_lib/src/fosns_velocity_ik.cpp
sns_ik_lib/src/fsns_velocity_ik.cpp

In FSNS and FOSNS, the SNSsingle function was setting the nullspace projection, P, equal to the Z matrix from the QR decomposition.
The correct mapping is:  P = Z * Z.transpose();

Correct nullspace projection for FSNS and FOSNS

---

sns_ik_lib/include/sns_ik/sns_ik.hpp
sns_ik_lib/src/sns_ik_math_utils.cpp

1) Pass vector by reference in getJointNames
2) Properly fill in matrix in pinv_forBarP

Two small bug fixes

---

sns_ik_examples/launch/test_ik_solvers.launch
sns_ik_examples/launch/test_sawyer.launch
sns_ik_examples/src/ik_tests.cpp

Copy of Baxter test script. Generates URDF from sawyer_robot package.
Resolves #61

Sawyer test launch script

---

sns_ik_examples/README.md
sns_ik_examples/config/example_sawyer_joint_limits.yaml
sns_ik_examples/launch/test_ik_solvers.launch
sns_ik_examples/src/ik_tests.cpp

This commit adds a missing yaml file that was preventing
test_sawyer.launch from running correctly. It also adds a
README.md file for the sns_ik_examples directory that shows
how to get the examples set up and running.

Add missing yaml file and document example

---

sns_ik_lib/include/sns_ik/fsns_velocity_ik.hpp
sns_ik_lib/include/sns_ik/sns_velocity_ik.hpp
sns_ik_lib/src/fosns_velocity_ik.cpp
sns_ik_lib/src/fsns_velocity_ik.cpp
sns_ik_lib/src/osns_velocity_ik.cpp
sns_ik_lib/src/sns_position_ik.cpp
sns_ik_lib/src/sns_velocity_ik.cpp

This commit standardizes the logging throughout the SNS-IK library
to use the ROS logging tools. It also includes some other minor
code clean-up.
Changes:
- All logging is now done using ROS logging tools
- Remove #define statements other than header guards
- Fix #include statements
- Remove some of the unused code
Issues: #38

Standardize to ROS logging throughout code

---

sns_ik_lib/LICENSE.txt
sns_ik_lib/matlab/LICENSE.txt
sns_ik_lib/matlab/README.md
sns_ik_lib/matlab/TEST_acc_ik_solvers.m
sns_ik_lib/matlab/TEST_vel_ik_solvers.m
sns_ik_lib/matlab/runTest_snsIk_acc.m
sns_ik_lib/matlab/runTest_snsIk_vel.m
sns_ik_lib/matlab/snsIk_acc_QP.m
sns_ik_lib/matlab/snsIk_acc_opt.m
sns_ik_lib/matlab/snsIk_acc_rr.m
sns_ik_lib/matlab/snsIk_vel_QP.m
sns_ik_lib/matlab/snsIk_vel_basic.m
sns_ik_lib/matlab/snsIk_vel_opt.m
sns_ik_lib/matlab/snsIk_vel_rr.m

This commit adds a few functions that implement various versions
of the SNS-IK solver algorithms, along with a set of unit tests.
This code is primarily used for reference and debugging, rather
than as a well-packaged product.

Added Matlab implementation of SNS-IK solvers

---

sns_ik_lib/CMakeLists.txt
sns_ik_lib/include/sns_ik/sns_vel_ik_base.hpp
sns_ik_lib/src/sns_vel_ik_base.cpp
sns_ik_lib/test/rng_utilities.cpp
sns_ik_lib/test/rng_utilities.hpp
sns_ik_lib/test/sns_vel_ik_base_test.cpp

New implementation of the SNS-IK velocity solver, with documentation,
unit tests, and a clean API. For now, the new implementation of the
solver is kept independent of the original code.

Initial work on SNS-IK velocity solver
